#!/usr/bin/env python3
"""
export_c.py — compile the trained model to a dependency-free C header.

Produces models/live_ids.h: the whole gradient-boosted tree ensemble as compact
`const` data plus a tiny `ids_predict()` walker. No onnxruntime, no libc math —
it runs on microcontrollers (ESP32-class) where a Python/ONNX runtime cannot.

There is no feature scaler: the model is trained on raw features because a tree
splits on `x < threshold` and is invariant to any strictly monotone per-feature
transform (see vault/Findings/F18). That removes the IDS_MEAN/IDS_SCALE tables
and 22 divisions per inference from the MCU path.

    #include "live_ids.h"
    float feats[IDS_NUM_FEATURES] = { ... };   // same 22 flow features
    int cls = ids_predict(feats);              // -> class id
    const char* name = IDS_LABELS[cls];

Inputs (produced by src/train_live_model.py):
    models/live_ids_booster.json   raw XGBoost booster
    models/live_meta.json          feature order, labels

Run:
    python src/export_c.py            # writes models/live_ids.h
    python src/export_c.py --verify   # gcc-compiles + checks parity vs the booster
"""
from __future__ import annotations

import os
import sys
import json
import argparse

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MODELS = os.path.join(ROOT, "models")


def _load():
    import xgboost as xgb
    meta = json.load(open(os.path.join(MODELS, "live_meta.json")))
    booster_path = os.path.join(MODELS, "live_ids_booster.json")
    if not os.path.exists(booster_path):
        sys.exit(f"[ERROR] {booster_path} missing — run src/train_live_model.py first")
    b = xgb.Booster()
    b.load_model(booster_path)
    df = b.trees_to_dataframe()
    return meta, df


def build_flat_trees(df, num_class):
    """Flatten every tree into a single node array + per-tree root/class."""
    nodes = []            # (feature, value, yes, no); leaf => feature=-1, value=leaf
    tree_root, tree_class = [], []
    for tid, g in df.groupby("Tree"):
        gg = g.set_index("Node")

        def add(node_num):
            row = gg.loc[node_num]
            idx = len(nodes)
            nodes.append(None)
            if row["Feature"] == "Leaf":
                nodes[idx] = (-1, float(row["Gain"]), -1, -1)
            else:
                f = int(str(row["Feature"])[1:])       # 'f12' -> 12
                thr = float(row["Split"])
                yes = int(str(row["Yes"]).split("-")[1])
                no = int(str(row["No"]).split("-")[1])
                yi = add(yes)
                ni = add(no)
                nodes[idx] = (f, thr, yi, ni)
            return idx

        tree_root.append(add(0))
        tree_class.append(int(tid) % num_class)
    return nodes, tree_root, tree_class


def _carr(vals, fmt="%d", per_line=20):
    out, line = [], []
    for i, v in enumerate(vals):
        line.append(fmt % v)
        if (i + 1) % per_line == 0:
            out.append(", ".join(line)); line = []
    if line:
        out.append(", ".join(line))
    return ",\n  ".join(out)


def generate_header(meta, df):
    nf = meta["n_features"]
    nc = meta["num_class"]
    labels = [meta["labels"][str(i)] for i in range(nc)]
    nodes, roots, classes = build_flat_trees(df, nc)

    node_lines = ",\n  ".join(
        "{%d, %.7ef, %d, %d}" % (f, v, y, n) for (f, v, y, n) in nodes)

    h = f"""/* live_ids.h — auto-generated by src/export_c.py. Do not edit by hand.
 * Dependency-free IoT-IDS model: {len(roots)} trees, {nc} classes,
 * {nf} features, {len(nodes)} nodes (~{len(nodes)*16//1024} KB of const data).
 * Usage:
 *     float feats[IDS_NUM_FEATURES] = {{ ... }};
 *     int cls = ids_predict(feats);          // class id
 *     const char* name = IDS_LABELS[cls];
 */
#ifndef LIVE_IDS_H
#define LIVE_IDS_H

#define IDS_NUM_FEATURES {nf}
#define IDS_NUM_CLASS {nc}
#define IDS_NUM_TREES {len(roots)}
#define IDS_NUM_NODES {len(nodes)}

static const char *IDS_LABELS[IDS_NUM_CLASS] = {{ {", ".join('"%s"' % l for l in labels)} }};

typedef struct {{ int feature; float value; int yes; int no; }} IdsNode;

static const IdsNode IDS_NODES[IDS_NUM_NODES] = {{
  {node_lines}
}};
static const int IDS_TREE_ROOT[IDS_NUM_TREES] = {{
  {_carr(roots, "%d")}
}};
static const unsigned char IDS_TREE_CLASS[IDS_NUM_TREES] = {{
  {_carr(classes, "%d")}
}};

/* Walk every tree; class score = sum of leaf outputs. The model is trained on
 * RAW features (trees are scale-invariant), so there is nothing to normalise.
 * Returns the arg-max class id (softmax arg-max == raw-margin arg-max, and the
 * scalar base_score shifts every class equally so it cannot change it). */
static int ids_predict(const float *x) {{
    int i, t, n, best;
    float score[IDS_NUM_CLASS];
    for (i = 0; i < IDS_NUM_CLASS; i++) score[i] = 0.0f;
    for (t = 0; t < IDS_NUM_TREES; t++) {{
        n = IDS_TREE_ROOT[t];
        while (IDS_NODES[n].feature >= 0)
            n = (x[IDS_NODES[n].feature] < IDS_NODES[n].value)
                ? IDS_NODES[n].yes : IDS_NODES[n].no;
        score[IDS_TREE_CLASS[t]] += IDS_NODES[n].value;
    }}
    best = 0;
    for (i = 1; i < IDS_NUM_CLASS; i++)
        if (score[i] > score[best]) best = i;
    return best;
}}

#endif /* LIVE_IDS_H */
"""
    return h, len(nodes)


def verify(meta):
    """Compile the C model and check parity against the raw XGBoost booster
    (the ground truth the header is generated from)."""
    import subprocess, tempfile, shutil
    import numpy as np
    import xgboost as xgb
    sys.path.insert(0, os.path.join(ROOT, "src"))
    sys.path.insert(0, os.path.join(ROOT, "attacks"))
    from flow_features import FlowTable, parse_raw
    import traffic_gen as tg

    if not shutil.which("gcc") and not shutil.which("cc"):
        print("[verify] no C compiler found — skipping compile check")
        return
    cc = shutil.which("gcc") or shutil.which("cc")

    # gather sample feature vectors across classes (unseen seeds)
    vecs = []
    for kind in tg.ATTACK_KINDS:
        variant = kind
        pkts = tg.generate(variant, seed=80000 + tg.LABELS.get(kind, 0))
        table = FlowTable()
        for p in sorted(pkts, key=lambda x: float(x.time)):
            pk = parse_raw(bytes(p))
            if pk:
                table.add_packet(pk, float(p.time))
        for _, v in table.extract(min_pkts=1)[:60]:
            vecs.append(v)
    X = np.asarray(vecs, dtype=np.float32)

    # ground truth: the booster's own prediction on the same raw inputs
    b = xgb.Booster()
    b.load_model(os.path.join(MODELS, "live_ids_booster.json"))
    ref_pred = np.argmax(b.predict(xgb.DMatrix(X)), axis=1)

    tmp = tempfile.mkdtemp(prefix="idsc_")
    shutil.copy(os.path.join(MODELS, "live_ids.h"), tmp)
    nf = meta["n_features"]
    rows = "\n".join(
        "{" + ",".join("%.7ef" % v for v in row) + "}," for row in X)
    c = f"""#include <stdio.h>
#include "live_ids.h"
static const float SAMPLES[{len(X)}][IDS_NUM_FEATURES] = {{
{rows}
}};
int main(void){{
    for (int i=0;i<{len(X)};i++) printf("%d\\n", ids_predict(SAMPLES[i]));
    return 0;
}}
"""
    open(os.path.join(tmp, "t.c"), "w").write(c)
    subprocess.run([cc, "-O2", "-o", os.path.join(tmp, "t"),
                    os.path.join(tmp, "t.c")], check=True)
    out = subprocess.run([os.path.join(tmp, "t")], capture_output=True, text=True)
    c_pred = np.array([int(l) for l in out.stdout.split()])
    agree = (c_pred == ref_pred).mean()
    print(f"[verify] C vs XGBoost booster on {len(X)} flows: {agree*100:.2f}%")
    shutil.rmtree(tmp, ignore_errors=True)
    if agree < 0.999:
        sys.exit("[verify] C export does NOT match the booster")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--verify", action="store_true",
                    help="gcc-compile and check parity against the XGBoost booster")
    args = ap.parse_args()
    meta, df = _load()
    header, n_nodes = generate_header(meta, df)
    out = os.path.join(MODELS, "live_ids.h")
    open(out, "w").write(header)
    kb = os.path.getsize(out) / 1024
    print(f"Wrote {out}  ({kb:.1f} KB source, {n_nodes} nodes, "
          f"{meta['num_class']} classes)")
    if args.verify:
        verify(meta)


if __name__ == "__main__":
    main()
